### ISSUE TITLE
fix HTML indentation/formatting

### ISSUE THREAD

**Issue by ad3429** [Julth/prj-rev-bwfs-dasmoto#4]
https://github.com/Julth/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20and%20Crafts/index.html#L7-L35

In certain areas of your HTML, your indentation/formatting seems to be a bit messy. Here is a great resource to look at for properly formatting your HTML:

https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/

**Comment by Julth** [comment]
Ammended
